generate_workflow.py: Apply tuxsuite if condition to all steps
There is a crash when running update_cache.py even if tuxsuite does not
run:

  Reading builds.json
  Traceback (most recent call last):
    File "update_cache.py", line 88, in <module>
      main()
    File "update_cache.py", line 58, in main
      raw = builds_json.read_text(encoding='utf-8')
    File "/usr/local/lib/python3.8/pathlib.py", line 1236, in read_text
      with self.open(mode='r', encoding=encoding, errors=errors) as f:
    File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open
      return io.open(self, mode, buffering, encoding, errors, newline,
    File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener
      return self._accessor.open(self, flags, mode)
  FileNotFoundError: [Errno 2] No such file or directory: 'builds.json'

None of the steps after tuxsuite need to run, so apply the same
condition to all steps.

Signed-off-by: Nathan Chancellor <nathan@kernel.org>