generator.yml: Drop clang-10 builds on mainline
Currently, mainline builds are broken with:

/builds/linux/mm/maccess.c:37:3: error: invalid output size for constraint '=a'
                copy_from_kernel_nofault_loop(dst, src, size, u64, Efault);
                ^
/builds/linux/mm/maccess.c:19:3: note: expanded from macro 'copy_from_kernel_nofault_loop'
                __get_kernel_nofault(dst, src, type, err_label);                \
                ^
/builds/linux/arch/x86/include/asm/uaccess.h:538:18: note: expanded from macro '__get_kernel_nofault'
        __get_user_size(*((type *)(dst)), (__force type __user *)(src), \
                        ^
/builds/linux/mm/maccess.c:37:3: error: invalid output size for constraint '=a'
/builds/linux/mm/maccess.c:19:3: note: expanded from macro 'copy_from_kernel_nofault_loop'
                __get_kernel_nofault(dst, src, type, err_label);                \
                ^
/builds/linux/arch/x86/include/asm/uaccess.h:538:18: note: expanded from macro '__get_kernel_nofault'
        __get_user_size(*((type *)(dst)), (__force type __user *)(src), \
                        ^
2 errors generated.

There is no problem with clang-11 and newer. clang-10 builds were
dropped for -next in PR #255 because we are raising the minimum
supported version of clang this release; do the same thing now even
though the kbuild tree has not been merged yet to keep the builds green.

Link: https://builds.tuxbuild.com/23dwDYSWgeinyJz5c3MDalzKPCs/build.log
Link: https://builds.tuxbuild.com/23dwDRYrVsjL8AffHmQHfiEERfP/build.log
Signed-off-by: Nathan Chancellor <nathan@kernel.org>